### ISSUE TITLE
General Feedback

### ISSUE THREAD

**Issue by philsinatra** [bschenerman/idm231#1]
## Audio Promise

> I'd like to do a promise to wait for the audio to be loaded before playing anything. I think it makes the most sense to wrap a promise around `handleFormSubmit()` but i just wanted to see if you agree or if i'm thinking about this the wrong way

I'd probably want to setup the sound handler as it's own function so that it does not impede using the rest of the interface if there's an issue with the audio download/stream.

You can setup the promise to verify the audio has downloaded enough data to begin streaming using the `canplaythrough` event, then create the `click` event listener.  That check could set a boolean which could then be referenced in your form submission handler. That way you basically have a toggle switch to turn sound effects off and on.

- [https://html.spec.whatwg.org/multipage/media.html#event-media-canplay](https://html.spec.whatwg.org/multipage/media.html#event-media-canplay)

## Lint Errors

I'm adding a screenshot of a linting error report so you can clean up your code:

![screen shot 2018-03-05 at 7 34 56 am](https://user-images.githubusercontent.com/1465808/36975331-c433fd2c-2047-11e8-88f0-4563575bbb64.png)

## Inline Styling

There are a few places you change the `display` property values in your JavaScript directly (example):

```javascript
const transitionScene = (hide, show) => {
  //utilize css transitions to smooth
  hide.setAttribute('style', 'display:none');
  show.setAttribute('style', 'display:inline-block');
}
```

Generally this is considered a bad practice. Change the display by manipulating classes and let the CSS file control the `display` values.

There is also an [HTML5 attribute `hidden`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden) that can be used to quickly show/hide content. You can easily manipulate this value in JavaScript:

```javascript
const myElement = document.getElementById('myElement');
myElement.hidden = true|false;
```

**Comment by bschenerman** [comment]
I'm realizing I should actually make use of the 'begin' button to preload all the audio and pictures. So how about:

```
onBeginClick()
  audioLoaded = setPromise()
    for each Sound obj: initializeAudio()
      //play btns render as inactive
      audioLoaded.then()
        activatePlayBtns()
      audioLoaded.catch()
        toggleAudioLoadFailureFeedbackElement()
```

I'll make use of a classList.toggle() to get the show/hide done in css.

I'm guessing a majority of those spaces and tabs and double quote strings are from the provided astroSign picker fn which I haven't bothered to clean up yet. As far as missing semicolons...yeah. I was taught js without semis so I still have that bad habit.

**Comment by philsinatra** [comment]
Why wait until the being button is clicked? Start loading the audio as soon as the page loads. You could have enough data downloaded before the start button is clicked to have all the sounds available.

I know you want to make your script technically advanced, but consider simply loading the audio in HTML elements at the bottom of your page. You can still reference, check status and control everything in JavaScript, but it will greatly simplify the loading process.

Controlling the loading of the audio dynamically is great when there's potential that some files will not be played, and therefore are not needed in every instance of the app. In this project, all the audio files will be required, so why not let them load as quickly as possible?

**Comment by bschenerman** [comment]
While reluctant, I'm willing to concede the advanced loading feature due to time pressure (it's more suited for the server class). However, I'm not quite sure I fully understand the control flow for the promise you're suggesting. When do I verify that the promise is resolved (or caught)?

**Comment by philsinatra** [comment]
Probably something like this:

1. page load begins
1. audio download begins
1. begin listening for when audio `canplaythrough`
1. promise `canplaythrough` fires (when true, resolve the promise)
1. execute promise _then_ function(s)
