### ISSUE TITLE
🐛 Feedback Display

### ISSUE THREAD

**Issue by philsinatra** [bschenerman/idm231#2]
> I'm having a really strange issue w my 231 project. js is able to correctly process an invalid str, and fire the function that attaches the proper feedback msg to the feedback element (and shows it). However it refuses to append to the DOM and I can't figure out why specifically, lines 208 and 209 of init.js aren't working as intended

Your code is executing, but then being overridden by [additional statements in your function](https://github.com/bschenerman/idm231/blob/master/js/init.js#L222-L223)

```javascript
    feedback.innerHTML = '';
    feedback.hidden = true;
```

---

Unrelated, you also have a [syntax error](https://github.com/bschenerman/idm231/blob/master/index.html#L22) (two double quotes) in your HTML:

```html
    <div class="edit-form">
      <a href="#"">Pick a Different Birthday</a>
    </div>
```

**Comment by bschenerman** [comment]
But shouldn't the `return false` on line 211 prevent that code from being reached?

**Comment by philsinatra** [comment]
That `return false` is within a function declaration:

```javascript
const err = (msg, feedback) => {
```

white means it will end execution of that specific function, not the parent function `validateNameFieldInp`.

**Comment by bschenerman** [comment]
ohhhh okay. I've always been a bit hazy has to how that works in terms of scope. I guess I have some reading to do.

I appended return statements to the control statements on lines 214 and 218 and all appears to be well.
